const PDFDocument = require("pdfkit");
const LearningPath = require("../models/LearningPath");
const User = require("../models/User");

// @desc    Export learning path as PDF
// @route   GET /api/export/pdf
// @access  Private
const exportPDF = async (req, res) => {
  try {
    const userId = req.user._id;
    const user = await User.findById(userId);
    const learningPath = await LearningPath.findOne({ userId });

    if (!learningPath) {
      return res
        .status(404)
        .json({ message: "No learning path found to export" });
    }

    // Create PDF document
    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=learning-path-${user.name.replace(/\s+/g, "-")}.pdf`,
    );

    // Pipe to response
    doc.pipe(res);

    // Title
    doc
      .fontSize(24)
      .fillColor("#2563eb")
      .text("Personalized Learning Path", { align: "center" });

    doc.moveDown();

    // User info
    doc
      .fontSize(12)
      .fillColor("#374151")
      .text(`Prepared for: ${user.name}`, { align: "center" });

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text(
        `Generated on: ${new Date(learningPath.generatedAt).toLocaleDateString()}`,
        { align: "center" },
      );

    doc.moveDown(2);

    // Progress summary
    doc
      .fontSize(14)
      .fillColor("#1f2937")
      .text("Progress Summary", { underline: true });

    doc.moveDown(0.5);

    doc
      .fontSize(11)
      .fillColor("#374151")
      .text(`Total Topics: ${learningPath.totalTopics}`)
      .text(`Completed: ${learningPath.completedTopics}`)
      .text(`Progress: ${learningPath.progressPercentage}%`);

    doc.moveDown(2);

    // Learning path topics
    doc
      .fontSize(16)
      .fillColor("#2563eb")
      .text("Your Learning Roadmap", { underline: true });

    doc.moveDown();

    // Topics
    learningPath.topics.forEach((topic, index) => {
      // Check if we need a new page
      if (doc.y > 700) {
        doc.addPage();
      }

      // Status indicator
      const statusColor =
        topic.status === "completed"
          ? "#10b981"
          : topic.status === "in_progress"
            ? "#f59e0b"
            : "#6b7280";
      const statusText =
        topic.status === "completed"
          ? "✓"
          : topic.status === "in_progress"
            ? "◐"
            : "○";

      // Topic header
      doc
        .fontSize(13)
        .fillColor(statusColor)
        .text(`${statusText} ${index + 1}. ${topic.title}`, {
          continued: false,
        });

      // Difficulty badge
      doc
        .fontSize(9)
        .fillColor("#6b7280")
        .text(`   Difficulty: ${topic.difficulty}`, { indent: 20 });

      // Description
      doc
        .fontSize(10)
        .fillColor("#374151")
        .text(`   ${topic.description}`, { indent: 20 });

      // Resources
      if (topic.resources && topic.resources.length > 0) {
        doc
          .fontSize(9)
          .fillColor("#2563eb")
          .text("   Resources:", { indent: 20 });

        topic.resources.slice(0, 3).forEach((resource) => {
          doc
            .fontSize(8)
            .fillColor("#4b5563")
            .text(`   • ${resource.title}`, { indent: 30 });

          if (resource.url) {
            doc
              .fontSize(7)
              .fillColor("#6b7280")
              .text(`     ${resource.url}`, { indent: 30 });
          }
        });
      }

      doc.moveDown();
    });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#9ca3af")
      .text("Generated by Personalized Learning Path Generator", {
        align: "center",
      })
      .text("Powered by AI Recommendations", { align: "center" });

    // Finalize PDF
    doc.end();
  } catch (error) {
    console.error("PDF export error:", error);
    res.status(500).json({ message: "Error generating PDF" });
  }
};

// @desc    Export learning path as JSON
// @route   GET /api/export/json
// @access  Private
const exportJSON = async (req, res) => {
  try {
    const learningPath = await LearningPath.findOne({ userId: req.user._id });

    if (!learningPath) {
      return res.status(404).json({ message: "No learning path found" });
    }

    const exportData = {
      exportedAt: new Date().toISOString(),
      progress: {
        completed: learningPath.completedTopics,
        total: learningPath.totalTopics,
        percentage: learningPath.progressPercentage,
      },
      topics: learningPath.topics.map((t) => ({
        title: t.title,
        description: t.description,
        difficulty: t.difficulty,
        status: t.status,
        resources: t.resources,
      })),
    };

    res.setHeader("Content-Type", "application/json");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=learning-path.json",
    );
    res.json(exportData);
  } catch (error) {
    console.error("JSON export error:", error);
    res.status(500).json({ message: "Error exporting data" });
  }
};

module.exports = { exportPDF, exportJSON };
